# Generated by Django 4.2.2 on 2023-06-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_password',
            field=models.CharField(default='', max_length=128, verbose_name='first password'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='second password'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
