# Generated by Django 4.2.2 on 2023-06-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='second_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
